name: Setup Node and Install Dependencies

description: Checkout repo, setup Node, and install dependencies with Yarn

runs:
  using: "composite"

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 25
        cache: yarn

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile
